// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC78tYo3LY4T3ERvudU3mKkOGof1z_3o9k',
    appId: '1:963772814263:web:61b09b5e1ab82e7457ce32',
    messagingSenderId: '963772814263',
    projectId: 'flutter-f4c93',
    authDomain: 'flutter-f4c93.firebaseapp.com',
    storageBucket: 'flutter-f4c93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqFlNlf_czr3J9lM27bJU5PNYWMM8DhiM',
    appId: '1:963772814263:android:bf95d8e2da645e3057ce32',
    messagingSenderId: '963772814263',
    projectId: 'flutter-f4c93',
    storageBucket: 'flutter-f4c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEghXGBXdDi8h1oaHdytqIUUe53enO5zI',
    appId: '1:963772814263:ios:d5b15d9c20ffc26357ce32',
    messagingSenderId: '963772814263',
    projectId: 'flutter-f4c93',
    storageBucket: 'flutter-f4c93.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEghXGBXdDi8h1oaHdytqIUUe53enO5zI',
    appId: '1:963772814263:ios:d5b15d9c20ffc26357ce32',
    messagingSenderId: '963772814263',
    projectId: 'flutter-f4c93',
    storageBucket: 'flutter-f4c93.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );
}
